language: node_js
sudo: required
node_js:
  - 10.8.0
install:
  - yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi'
